apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-dev-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: voting-dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voting-dev
            port:
              number: 8080
